import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers';

import Providers from '@/redux/provider'

import './globals.css'
import Structure from '@/components/structure'
import config from '@/config';
import { Toaster } from '@/components/ui/toaster';
import { getServerSession } from 'next-auth';
import { nextAuthOptions } from './api/auth/[...nextauth]/authOptions';
// import '@/components/editor/wysiwyg/style.scss'

// Add your custom fonts here
const inter = Inter({ subsets: ['latin'] })

// Define default titles for SEO
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await getServerSession(nextAuthOptions);

    const cookieStore = cookies();
    const theme = cookieStore.get(config.theme_key);

    if (session && session.user.permissions?.view_dashboard && session.user.permissions.visit_admin_panel)
        return (
            <html lang='en'>
                <body className={`${inter.className} ${theme?.value || "dark"}`}>
                    <Providers theme={theme?.value} session={session}>
                        <Structure theme={theme?.value || ""}>
                            {children}
                            <Toaster />
                        </Structure>
                    </Providers>
                </body>
            </html>
        )
    else
        return (
            <html lang='en'>
                <body className={`${inter.className} ${theme?.value || "dark"}`}>
                    <Providers theme={theme?.value} session={session}>
                        <h1 className="text-4xl text-center pt-20">
                            You are not authorized to view this page
                        </h1>
                        <Toaster />
                    </Providers>
                </body>
            </html>
        );
}
