import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers';

import Providers from '@/redux/provider'

import './globals.css'
import Structure from '@/components/structure'
import config from '@/config';
import { Toaster } from '@/components/ui/toaster';
// import '@/components/editor/wysiwyg/style.scss'

// Add your custom fonts here
const inter = Inter({ subsets: ['latin'] })

// Define default titles for SEO
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = cookies();
    const theme = cookieStore.get(config.theme_key);

    return (
        // <html lang="en" className={theme?.value || "dark"}>
        <html lang='en'>
            <body className={`${inter.className} ${theme?.value || "dark"}`}>
                <Providers theme={theme?.value}>
                    <Structure theme={theme?.value || ""}>
                        {children}
                        <Toaster />
                    </Structure>
                </Providers>
            </body>
        </html>
    )
}
